apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-nvpknwwe
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-nvpknwwe:49313239ea549d7447a5a87d8b4c6aeca3fa332e@sha256:0c8b356e10b4ddb2a1b87d02ff7aad8122dc0d7269ad04947f5e90eb4bf6994f
          name: container-image
